# Generated by Django 5.1.6 on 2025-02-23 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'estudiante'}, related_name='assigned_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_answer',
            field=models.JSONField(blank=True, help_text='Lista de respuestas correctas en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='options',
            field=models.JSONField(blank=True, help_text='Lista de opciones en formato JSON', null=True),
        ),
    ]
