# Generated by Django 5.1.6 on 2025-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_exercise_assigned_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_answer',
            field=models.JSONField(blank=True, default=list, help_text='Lista de respuestas correctas en formato JSON', null=True),
        ),
    ]
