# Generated by Django 5.1.6 on 2025-02-23 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_remove_exercise_user_alter_exercise_correct_answer'),
        ('vocabulario', '0002_remove_word_definition_word_translation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='word',
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='words',
            field=models.ManyToManyField(blank=True, help_text='Selecciona las palabras involucradas en este ejercicio.', related_name='exercises', to='vocabulario.word'),
        ),
    ]
