# Generated by Django 5.1.6 on 2025-02-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ejercicios", "0004_remove_exercise_word_exercise_user_exercise_words"),
        ("vocabulario", "0002_remove_word_definition_word_translation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="words",
        ),
        migrations.AddField(
            model_name="exercise",
            name="words_json",
            field=models.JSONField(
                blank=True,
                help_text="Pares de palabras en formato JSON (usado para ejercicios de emparejamiento). Ej: [['gato','cat'], ['perro','dog'], ['sol','sun'], ['luna','moon']]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="words_m2m",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selecciona las palabras involucradas (usado para ejercicios de selección múltiple).",
                related_name="exercises",
                to="vocabulario.word",
            ),
        ),
    ]
